"""Executor — runs executable_plan steps from actions via MCP tools.

Takes a JSON plan (generated by LLM), iterates steps, invokes tools,
records results as events.
"""

import json

from app.core.harness.mcp_hub import mcp_hub
from app.core.runtime.event_bus import EventType, event_bus
from app.core.telemetry.event_recorder import Event, event_recorder
from app.store.database import db


class Executor:
    """Executes LLM-generated action plans step by step."""

    async def execute_action(self, action_id: str) -> dict:
        """Execute an action's executable_plan, recording each step result as an event."""
        with db.get_db() as conn:
            row = conn.execute("SELECT * FROM actions WHERE id = ?", (action_id,)).fetchone()
        if not row:
            return {"error": "Action not found"}

        action = dict(row)
        plan_str = action.get("executable_plan")
        if not plan_str:
            return {"error": "No executable plan defined"}

        try:
            plan = json.loads(plan_str)
        except json.JSONDecodeError:
            return {"error": "Invalid plan JSON"}

        steps = plan.get("steps", [])
        results = []
        previous_output: dict[str, object] = {}

        for i, step in enumerate(steps):
            tool_name = step["tool"]
            params = step.get("params", {})

            # Inject previous step's output if this step depends on it
            if step.get("depends_on_output") and previous_output:
                params["_previous_output"] = previous_output

            try:
                tool_result = await mcp_hub.invoke_tool(tool_name, params)
                step_status = "success"
            except Exception as e:
                tool_result = json.dumps({"error": str(e)})
                step_status = "failed"

            results.append({
                "step": i,
                "tool": tool_name,
                "status": step_status,
                "result_preview": tool_result[:500],
            })

            # Record step event
            event_recorder.record(Event(
                type="execution_step",
                summary=f"Step {i}: {tool_name} ({step_status})",
                payload={
                    "action_id": action_id,
                    "step_index": i,
                    "tool": tool_name,
                    "status": step_status,
                },
            ))

            previous_output = {"step_{i}_output": tool_result[:1000]}

            if step_status == "failed" and not step.get("continue_on_error"):
                break

        event_bus.publish(EventType.TASK_COMPLETED, {
            "task_id": f"action-{action_id}",
            "name": f"Executed action: {action.get('title', '')}",
            "step_results": results,
        })

        return {
            "action_id": action_id,
            "total_steps": len(steps),
            "completed_steps": len([r for r in results if r["status"] == "success"]),
            "results": results,
        }

    def generate_executable_plan(self, action_title: str, tool_context: str = "") -> dict:
        """Generate an executable plan JSON for a text action title (template-based).

        In production, this would call the LLM to translate natural language into a step plan.
        This stub provides a basic template for common action patterns.
        """
        return {
            "steps": [
                {
                    "tool": "web_search",
                    "params": {"query": action_title},
                    "depends_on_output": False,
                    "continue_on_error": False,
                },
            ]
        }


executor = Executor()
