/**
 * Electron main process for Personal AI Runtime Desktop.
 *
 * Provides:
 * - System tray icon with quick actions
 * - Global shortcut (Alt+Space) for quick chat
 * - Quick capture (Alt+Shift+I) for Inbox
 * - Native notifications
 * - Auto-start on login
 * - Backend process management (auto-start/stop)
 * - Loads the web app in a frameless window
 */

const { app, BrowserWindow, Tray, Menu, globalShortcut, Notification, dialog, nativeImage } = require("electron");
const { spawn } = require("child_process");
const fs = require("fs");
const path = require("path");

// ── Configuration ────────────────────────────────────────────────────

const WEB_URL = process.env.WEB_URL || "http://localhost:5173";
const BACKEND_URL = process.env.BACKEND_URL || "http://localhost:8000";
const BACKEND_PORT = new URL(BACKEND_URL).port || "8000";
const AUTH_TOKEN = process.env.AUTH_TOKEN || "";

function readAppVersion() {
  try {
    const versionPath = path.join(__dirname, "..", "VERSION");
    return fs.readFileSync(versionPath, "utf8").trim();
  } catch {
    return "0.9.0";
  }
}

const APP_VERSION = readAppVersion();

// ── Backend Process Management ───────────────────────────────────────

let backendProcess = null;
let backendStarting = false;

function startBackend() {
  if (backendProcess || backendStarting) return;

  backendStarting = true;
  const repoRoot = path.join(__dirname, "..");
  const backendDir = path.join(repoRoot, "backend");

  // Check if backend is already running
  const net = require("net");
  const client = new net.Socket();
  client.connect(parseInt(BACKEND_PORT), "localhost", () => {
    client.destroy();
    console.log("Backend already running on port", BACKEND_PORT);
    backendStarting = false;
  });

  client.on("error", () => {
    client.destroy();
    console.log("Starting backend...");

    backendProcess = spawn("python3", ["-m", "uvicorn", "app.main:app", "--host", "127.0.0.1", "--port", BACKEND_PORT], {
      cwd: backendDir,
      env: { ...process.env },
      stdio: ["ignore", "pipe", "pipe"],
    });

    backendProcess.stdout.on("data", (data) => {
      console.log("[backend]", data.toString().trim());
    });

    backendProcess.stderr.on("data", (data) => {
      console.log("[backend]", data.toString().trim());
    });

    backendProcess.on("close", (code) => {
      console.log("Backend exited with code", code);
      backendProcess = null;
    });

    backendProcess.on("error", (err) => {
      console.error("Backend start error:", err.message);
      backendProcess = null;
    });

    backendStarting = false;
  });
}

function stopBackend() {
  if (backendProcess) {
    console.log("Stopping backend...");
    backendProcess.kill("SIGTERM");
    setTimeout(() => {
      if (backendProcess) {
        backendProcess.kill("SIGKILL");
        backendProcess = null;
      }
    }, 5000);
  }
}

// ── Window State ─────────────────────────────────────────────────────

let mainWindow = null;
let miniWindow = null;
let tray = null;
let isQuitting = false;

function createTrayIcon() {
  // Use the generated icon.png if available, otherwise fall back to a colored square
  const iconPath = path.join(__dirname, "icon.png");
  let trayIcon;
  try {
    if (fs.existsSync(iconPath)) {
      trayIcon = nativeImage.createFromPath(iconPath);
      // macOS tray icons should be small
      if (process.platform === "darwin") {
        trayIcon = trayIcon.resize({ width: 16, height: 16 });
      }
    } else {
      trayIcon = createFallbackIcon();
    }
  } catch {
    trayIcon = createFallbackIcon();
  }
  return trayIcon;
}

function createFallbackIcon() {
  // Fallback: empty 16x16 icon (icon.png should be generated by postinstall script)
  return nativeImage.createEmpty();
}

function createMainWindow() {
  const iconPath = path.join(__dirname, "icon.png");
  const winOpts = {
    width: 1200,
    height: 800,
    minWidth: 800,
    minHeight: 600,
    title: "Personal AI Runtime",
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, "preload.js"),
    },
    frame: true,
    show: false,
  };
  if (fs.existsSync(iconPath)) {
    winOpts.icon = iconPath;
  }

  mainWindow = new BrowserWindow(winOpts);
  mainWindow.loadURL(WEB_URL);

  mainWindow.on("ready-to-show", () => {
    mainWindow.show();
  });

  mainWindow.on("close", (event) => {
    if (!isQuitting) {
      event.preventDefault();
      mainWindow.hide();
    }
  });

  mainWindow.on("closed", () => {
    mainWindow = null;
  });
}

function createMiniWindow() {
  if (miniWindow) {
    miniWindow.focus();
    return;
  }

  miniWindow = new BrowserWindow({
    width: 600,
    height: 500,
    resizable: true,
    frame: false,
    alwaysOnTop: true,
    skipTaskbar: true,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, "preload.js"),
    },
  });

  miniWindow.loadURL(WEB_URL);

  miniWindow.on("blur", () => {
    if (miniWindow) {
      miniWindow.close();
      miniWindow = null;
    }
  });

  miniWindow.on("closed", () => {
    miniWindow = null;
  });
}

function createTray() {
  tray = new Tray(createTrayIcon());

  const contextMenu = Menu.buildFromTemplate([
    {
      label: "打开 Personal AI Runtime",
      click: () => {
        if (mainWindow) {
          mainWindow.show();
          mainWindow.focus();
        } else {
          createMainWindow();
        }
      },
    },
    {
      label: "快捷对话 (Alt+Space)",
      click: () => createMiniWindow(),
    },
    { type: "separator" },
    {
      label: backendProcess ? "重启后端" : "启动后端",
      click: () => {
        stopBackend();
        setTimeout(startBackend, 1000);
      },
    },
    { type: "separator" },
    {
      label: "关于",
      click: () => {
        const statusText = backendProcess ? "后端运行中" : "后端未运行（需手动启动 backend）";
        dialog.showMessageBox({
          type: "info",
          title: "Personal AI Runtime",
          message: `Personal AI Runtime v${APP_VERSION}`,
          detail: `${statusText}\n数据存于本机，完全私有`,
        });
      },
    },
    { type: "separator" },
    {
      label: "退出",
      click: () => {
        isQuitting = true;
        stopBackend();
        app.quit();
      },
    },
  ]);

  tray.setToolTip("Personal AI Runtime");
  tray.setContextMenu(contextMenu);

  tray.on("click", () => {
    if (mainWindow) {
      mainWindow.isVisible() ? mainWindow.hide() : mainWindow.show();
    }
  });
}

function registerGlobalShortcuts() {
  globalShortcut.register("Alt+Space", () => {
    createMiniWindow();
  });

  globalShortcut.register("Alt+Shift+I", () => {
    quickCapture();
  });
}

async function quickCapture() {
  if (mainWindow) {
    mainWindow.show();
    mainWindow.focus();
  } else {
    createMainWindow();
  }
  if (mainWindow) {
    mainWindow.webContents.executeJavaScript(`
      window.postMessage({ type: 'quick-capture' }, '*');
    `);
  }
}

function showNotification(title, body) {
  if (Notification.isSupported()) {
    const notification = new Notification({ title, body });
    notification.show();
    notification.on("click", () => {
      if (mainWindow) {
        mainWindow.show();
        mainWindow.focus();
      } else {
        createMainWindow();
      }
    });
  }
}

// ── App Lifecycle ────────────────────────────────────────────────────

app.whenReady().then(() => {
  // Auto-start backend
  startBackend();

  createMainWindow();
  createTray();
  registerGlobalShortcuts();
  connectWebSocket();

  app.on("activate", () => {
    if (mainWindow === null) {
      createMainWindow();
    } else {
      mainWindow.show();
    }
  });
});

app.on("window-all-closed", () => {
  // Keep running in tray
});

app.on("before-quit", () => {
  isQuitting = true;
  globalShortcut.unregisterAll();
  stopBackend();
});

app.setLoginItemSettings({
  openAtLogin: true,
  openAsHidden: true,
});

// ── WebSocket ────────────────────────────────────────────────────────

function connectWebSocket() {
  try {
    const WebSocket = require("ws");
    const wsUrl = BACKEND_URL.replace(/^http/, "ws") + "/ws";
    const protocols = AUTH_TOKEN ? [`auth.${AUTH_TOKEN}`, "auth.ok"] : undefined;
    const ws = protocols ? new WebSocket(wsUrl, protocols) : new WebSocket(wsUrl);

    ws.on("open", () => {
      console.log("WebSocket connected for notifications");
    });

    ws.on("message", (data) => {
      try {
        const event = JSON.parse(data.toString());
        if (event.type === "notification") {
          showNotification(event.title, event.content);
        }
      } catch {
        // Ignore parse errors
      }
    });

    ws.on("close", () => {
      setTimeout(connectWebSocket, 5000);
    });

    ws.on("error", () => {
      setTimeout(connectWebSocket, 10000);
    });
  } catch {
    // WebSocket not available, skip
  }
}

// ── IPC ──────────────────────────────────────────────────────────────

const { ipcMain } = require("electron");

ipcMain.handle("get-backend-url", () => BACKEND_URL);

ipcMain.handle("send-notification", (_event, { title, body }) => {
  showNotification(title, body);
});
